### PR TITLE
pdal 3.5

### PR DESCRIPTION
**Pull request by runette**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by runette** [comment]
@conda-forge-admin, please rerender

**Comment by hobu** [comment]
PipelineExecutor was deprecated and the noise is causing a compilation/linking error for Windows and Linux. I don't know what PDAL-C is going to do about deprecations, but we weren't intending to remove PipelineExecutor for a while.

**Comment by runette** [comment]
I had noticed the depreciation and thought the same thing.

I need to think about how to approach this. The correct thing would be to
address the delegation now - I hate to leave technical debt to build up. I
am just not sure that I have the time in the next couple of weeks.

**Comment by runette** [comment]
This pipeline has been updated to CVAP 2.2.0 to solve the problem ith deprecation 👍 
https://github.com/PDAL/CAPI/releases/tag/v2.2.0

**Pull request merged**
